import AppKit
import Foundation

/// Plain-text clipboard in both directions, bounded to 16 KiB. Mac → client is opt-in per session, reports only
/// changes made after the session started, and skips items password managers mark as concealed or transient.
/// Clipboard text is never logged.
final class Clipboard {
    static let maxBytes = 16 * 1024
    private static let skippedTypes: Set<String> = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                                                    "org.nspasteboard.AutoGeneratedType"]
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var timer: DispatchSourceTimer?

    /// Client → Mac. Returns false when the text is empty or too large.
    func set(_ text: String) -> Bool {
        guard !text.isEmpty, text.utf8.count <= Clipboard.maxBytes else { return false }
        DispatchQueue.main.sync {
            let pasteboard = NSPasteboard.general
            pasteboard.clearContents()
            pasteboard.setString(text, forType: .string)
            lastChangeCount = pasteboard.changeCount // our own write is not echoed back to the client
        }
        return true
    }

    /// Mac → client. Polls the change count (NSPasteboard has no change notification).
    func watch(queue: DispatchQueue, onChange: @escaping (String) -> Void) {
        DispatchQueue.main.sync { lastChangeCount = NSPasteboard.general.changeCount }
        let timer = DispatchSource.makeTimerSource(queue: queue)
        timer.schedule(deadline: .now() + 0.5, repeating: 0.5)
        timer.setEventHandler { [weak self] in
            guard let self else { return }
            var text: String?
            DispatchQueue.main.sync {
                let pasteboard = NSPasteboard.general
                guard pasteboard.changeCount != self.lastChangeCount else { return }
                self.lastChangeCount = pasteboard.changeCount
                let types = Set((pasteboard.types ?? []).map(\.rawValue))
                guard types.isDisjoint(with: Clipboard.skippedTypes), let value = pasteboard.string(forType: .string),
                      !value.isEmpty, value.utf8.count <= Clipboard.maxBytes else { return }
                text = value
            }
            if let text { onChange(text) }
        }
        timer.resume()
        self.timer = timer
    }

    func stop() { timer?.cancel(); timer = nil }
}
