import test from 'node:test';
import assert from 'node:assert/strict';
import {KeyboardState, mapLogicalKey} from './keyboard-state.mjs';
const setup = (profile='mac-native') => { const events=[]; return {events, state:new KeyboardState({profile,onTransition:e=>events.push(e)})}; };
const event=(key,down)=>({key,down});
test('Mac Command stays Command',()=>assert.equal(mapLogicalKey('mac-native','CommandLeft',{code:'MetaLeft'}),'CommandLeft'));
test('Windows native Alt stays Option',()=>assert.equal(mapLogicalKey('windows-native','OptionLeft',{code:'AltLeft'}),'OptionLeft'));
test('Opt-in Left Alt becomes Command',()=>assert.equal(mapLogicalKey('windows-alt-command','OptionLeft',{code:'AltLeft'}),'CommandLeft'));
test('Opt-in Right Alt is not converted',()=>assert.equal(mapLogicalKey('windows-alt-command','OptionRight',{code:'AltRight'}),'OptionRight'));
test('Control remains Control in every profile',()=>{for(const p of ['mac-native','windows-native','windows-alt-command'])assert.equal(mapLogicalKey(p,'ControlLeft',{code:'ControlLeft'}),'ControlLeft');});
test('Virtual Option is never profile-remapped',()=>assert.equal(mapLogicalKey('windows-alt-command','OptionLeft',{code:'AltLeft',physical:false}),'OptionLeft'));
test('Unknown profile is rejected',()=>assert.throws(()=>setup('magic'),RangeError));
test('Missing transition sink is rejected',()=>assert.throws(()=>new KeyboardState(),TypeError));
test('Simple down and up pair',()=>{const {state,events}=setup();state.down('p:KeyA','a');state.up('p:KeyA');assert.deepEqual(events,[event('a',true),event('a',false)]);});
test('Repeat cannot add an owner',()=>{const {state,events}=setup();state.down('p:A','a');assert.equal(state.down('p:A','A'),false);state.up('p:A');assert.equal(events.length,2);});
test('Keyup uses original logical snapshot',()=>{const {state,events}=setup();state.down('p:A','A');state.down('p:A','a');state.up('p:A');assert.equal(events.at(-1).key,'A');});
test('Unowned keyup does nothing',()=>{const {state,events}=setup();assert.equal(state.up('missing'),false);assert.equal(events.length,0);});
test('Two physical aliases keep Command held',()=>{const {state,events}=setup('windows-alt-command');state.down('p:AltLeft','OptionLeft',{code:'AltLeft'});state.down('p:MetaLeft','CommandLeft',{code:'MetaLeft'});state.up('p:AltLeft');assert.deepEqual(events,[event('CommandLeft',true)]);state.up('p:MetaLeft');assert.deepEqual(events,[event('CommandLeft',true),event('CommandLeft',false)]);});
test('Profile switch releases original mapping first',()=>{const {state,events}=setup('windows-alt-command');state.down('p:AltLeft','OptionLeft',{code:'AltLeft'});state.setProfile('windows-native');assert.deepEqual(events,[event('CommandLeft',true),event('CommandLeft',false)]);assert.deepEqual(state.snapshot().remoteHeld,[]);});
test('Invalid profile switch does not mutate held keys',()=>{const {state}=setup();state.down('p:A','a');assert.throws(()=>state.setProfile('x'));assert.deepEqual(state.snapshot().remoteHeld,['a']);});
test('Same profile does not unexpectedly release keys',()=>{const {state}=setup();state.down('p:A','a');assert.equal(state.setProfile('mac-native'),false);assert.equal(state.snapshot().sources.length,1);});
test('Release all is reverse acquisition order',()=>{const {state,events}=setup();state.down('p:Shift','ShiftLeft');state.down('p:A','A');state.releaseAll();assert.deepEqual(events.slice(2),[event('A',false),event('ShiftLeft',false)]);});
test('Release all handles alias count and is idempotent',()=>{const {state,events}=setup();state.down('one','CommandLeft');state.down('two','CommandLeft');state.releaseAll();state.releaseAll();assert.deepEqual(events,[event('CommandLeft',true),event('CommandLeft',false)]);});
test('Virtual chord has balanced transitions',()=>{const {state,events}=setup();state.virtualChord(['CommandLeft','c']);assert.deepEqual(events,[event('CommandLeft',true),event('c',true),event('c',false),event('CommandLeft',false)]);assert.equal(state.snapshot().sources.length,0);});
test('Virtual chord rejects held physical input',()=>{const {state}=setup();state.down('p:A','a');assert.throws(()=>state.virtualChord(['CommandLeft','c']),/Release physical/);});
test('Virtual chord preserves previously latched ownership',()=>{const {state,events}=setup();state.down('latch','CommandLeft',{physical:false});state.virtualChord(['CommandLeft','c']);assert.deepEqual(state.snapshot().remoteHeld,['CommandLeft']);assert.equal(events.filter(e=>e.key==='CommandLeft'&&!e.down).length,0);state.releaseAll();});
test('Duplicate and empty chords are rejected',()=>{const {state}=setup();assert.throws(()=>state.virtualChord([]));assert.throws(()=>state.virtualChord(['c','c']));});
test('Invalid input fails before state changes',()=>{const {state}=setup();assert.throws(()=>state.down('','x'));assert.throws(()=>state.down('p',''));assert.throws(()=>state.down('p','x',{physical:'yes'}));assert.equal(state.snapshot().sources.length,0);});
test('Sink error clears state and permanently ends this instance',()=>{const state=new KeyboardState({onTransition:()=>{throw new Error('network');}});assert.throws(()=>state.down('a','a'),/delivery is unknown/);assert.equal(state.broken,true);assert.equal(state.snapshot().sources.length,0);assert.throws(()=>state.down('b','b'),/fresh session/);});
test('Sink error on release also fails closed',()=>{let calls=0;const state=new KeyboardState({onTransition:()=>{if(++calls===2)throw new Error('gone');}});state.down('a','a');assert.throws(()=>state.up('a'));assert.deepEqual(state.snapshot().remoteHeld,[]);assert.equal(state.broken,true);});
test('Snapshot mutation cannot alter internal state',()=>{const {state}=setup();state.down('p:A','a');const s=state.snapshot();s.sources[0].key='bad';s.remoteHeld.length=0;assert.deepEqual(state.snapshot().remoteHeld,['a']);});
