import test from 'node:test'; import assert from 'node:assert/strict';
import {exactOriginAllowed, makeDeadline, evaluateSession, evaluateIntent} from './session-policy.mjs';
const base={createdAtMs:1000,lastInputAtMs:1000,deadlineMs:3_601_000,nowMs:2000};
const intent={id:'i',ownerId:'o',appSessionId:'s',nodeId:'n',deviceId:'d',mode:'control',createdAtMs:1000,expiresAtMs:31000,consumedAtMs:null,revoked:false};
const req={...intent,sessionActive:true};
test('Exact HTTPS origin is accepted',()=>assert.equal(exactOriginAllowed('https://remote-mini.example.com','https://remote-mini.example.com'),true));
for(const origin of ['null','https://evil.example.com','https://remote-mini.example.com.evil.test','https://remote-mini.example.com/','http://remote-mini.example.com','']) test(`Origin rejected: ${origin}`,()=>assert.equal(exactOriginAllowed(origin,'https://remote-mini.example.com'),false));
test('Malformed expected origin cannot authorize',()=>{for(const e of ['http://localhost','https://a.example/path','https://u:p@a.example','not a url']) assert.equal(exactOriginAllowed(e,e),false);});
test('Deadline bound to earlier verified Access expiry',()=>assert.equal(makeDeadline({createdAtMs:1000,verifiedAccessExpiryMs:2000}),2000));
test('Deadline capped to one-hour design default',()=>assert.equal(makeDeadline({createdAtMs:1000,verifiedAccessExpiryMs:99_000_000}),3_601_000));
test('Expired identity cannot bootstrap',()=>assert.throws(()=>makeDeadline({createdAtMs:1000,verifiedAccessExpiryMs:1000})));
test('NaN/negative/overflow deadline rejected',()=>{assert.throws(()=>makeDeadline({createdAtMs:NaN,verifiedAccessExpiryMs:100}));assert.throws(()=>makeDeadline({createdAtMs:-1,verifiedAccessExpiryMs:100}));assert.throws(()=>makeDeadline({createdAtMs:Number.MAX_SAFE_INTEGER-5,verifiedAccessExpiryMs:Number.MAX_SAFE_INTEGER,capMs:10}));});
test('Valid active session',()=>assert.deepEqual(evaluateSession(base),{allowed:true,reason:'ACTIVE'}));
test('Absolute deadline is exclusive',()=>assert.equal(evaluateSession({...base,nowMs:3_601_000,lastInputAtMs:3_600_999}).reason,'ABSOLUTE_EXPIRED'));
test('Input idle timeout even with no notion of heartbeat',()=>assert.equal(evaluateSession({...base,nowMs:901000}).reason,'IDLE_EXPIRED'));
test('Revocation overrides otherwise active state',()=>assert.equal(evaluateSession({...base,revoked:true}).reason,'REVOKED'));
test('Future or precreation activity fails closed',()=>{assert.equal(evaluateSession({...base,lastInputAtMs:3000}).reason,'INVALID_STATE');assert.equal(evaluateSession({...base,lastInputAtMs:999}).reason,'INVALID_STATE');});
test('Invalid zero idle fails closed',()=>assert.equal(evaluateSession({...base,idleMs:0}).allowed,false));
test('Valid intent only eligible, not consumed by predicate',()=>{assert.equal(evaluateIntent(intent,req,2000).reason,'ELIGIBLE_FOR_ATOMIC_CONSUME');assert.equal(intent.consumedAtMs,null);});
for(const field of ['id','ownerId','appSessionId','nodeId','deviceId'])test(`Intent rejects mismatched ${field}`,()=>assert.equal(evaluateIntent(intent,{...req,[field]:'other'},2000).reason,'BINDING_MISMATCH'));
test('Intent does not permit mode escalation',()=>assert.equal(evaluateIntent({...intent,mode:'view'},req,2000).reason,'MODE_MISMATCH'));
test('Intent rejects exact expiry boundary',()=>assert.equal(evaluateIntent(intent,req,31000).reason,'EXPIRED'));
test('Intent rejects reuse',()=>assert.equal(evaluateIntent({...intent,consumedAtMs:1500},req,2000).reason,'ALREADY_USED'));
test('Intent rejects revocation and inactive owner session',()=>{assert.equal(evaluateIntent({...intent,revoked:true},req,2000).allowed,false);assert.equal(evaluateIntent(intent,{...req,sessionActive:false},2000).allowed,false);});
test('Intent rejects excessive TTL and future creation',()=>{assert.equal(evaluateIntent({...intent,expiresAtMs:32000},req,2000).reason,'INVALID_INTENT');assert.equal(evaluateIntent(intent,req,999).reason,'INVALID_INTENT');});
test('Incomplete intent fields fail closed',()=>{const i={...intent};delete i.revoked;assert.equal(evaluateIntent(i,req,2000).allowed,false);assert.equal(evaluateIntent(null,req,2000).allowed,false);});
